# Generated by Django 5.2.5 on 2025-08-19 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(choices=[('ALERGOLOGIA', 'Alergología'), ('CARDIOLOGIA', 'Cardiología'), ('DERMATOLOGIA', 'Dermatología'), ('ENDOCRINOLOGIA', 'Endocrinología'), ('GASTROENTEROLOGIA', 'Gastroenterología'), ('GERIATRIA', 'Geriatría'), ('GINECOLOGIA', 'Ginecología'), ('HEMATOLOGIA', 'Hematología'), ('INFECTOLOGIA', 'Infectología'), ('MEDICINA_GENERAL', 'Medicina General'), ('MEDICINA_INTERNA', 'Medicina Interna'), ('NEUMOLOGIA', 'Neumología'), ('NEFROLOGIA', 'Nefrología'), ('NEUROLOGIA', 'Neurología'), ('NUTRIOLOGIA', 'Nutriología'), ('OFTALMOLOGIA', 'Oftalmología'), ('ONCOLOGIA', 'Oncología'), ('ORTOPEDIA', 'Ortopedia'), ('OTORRINOLARINGOLOGIA', 'Otorrinolaringología'), ('PEDIATRIA', 'Pediatría'), ('PSIQUIATRIA', 'Psiquiatría'), ('RADIOLOGIA', 'Radiología'), ('REUMATOLOGIA', 'Reumatología'), ('TRAUMATOLOGIA', 'Traumatología'), ('UROLOGIA', 'Urología')], default='ALERGOLOGIA', max_length=21)),
                ('exequatur', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('aseguradora', models.CharField(choices=[('PRIVADO', 'Privado'), ('ARS_CMD', 'ARS CMD'), ('ARS_CONSTITUCION', 'ARS Constitución'), ('ARS_FUTURO', 'ARS Futuro'), ('ARS_HUMANO', 'ARS Humano'), ('ARS_INDEPENDIENTE', 'ARS Independiente'), ('ARS_MAPFRE', 'ARS MAPFRE Salud'), ('ARS_MAEP', 'ARS MAEP'), ('ARS_META_SALUD', 'ARS Meta Salud'), ('ARS_MUNICIPAL', 'ARS SEMMA / Municipal'), ('ARS_PALIC', 'ARS Palic'), ('ARS_PEPSICO', 'ARS PepsiCo'), ('ARS_PRESIDENCIAL', 'ARS Primera ARS de Humano'), ('ARS_RESERVAS', 'ARS Reservas'), ('ARS_SIMAG', 'ARS SIMAG'), ('ARS_UNIVERSAL', 'ARS Universal'), ('ARS_YUNEN', 'ARS Yunen'), ('PARTICULAR', 'Particular (sin ARS)'), ('OTRA', 'Otra')], default='PRIVADO', max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='femenino', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('AUSENTE', 'Ausente')], default='AGENDADA', max_length=50)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.paciente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'dia_semana')},
            },
        ),
    ]
